### PR TITLE
Fix unrestricted access that is given to `Acru'

### PR DESCRIPTION
**Pull request by Hidendra**
Hello.

In the current release version (that is, 1.6 and the fork 1.7) there exists code that permits unrestricted access to the following:
- Interaction of any Lockette-protected sign to allow selection for editing
- The command `/lockette` (that is, allowing the editing of any line on a Lockette-protected sign)

Used in combination, one could assign themselves membership to any Lockette-protected block. Afterwards, they could in theory simply remove themselves once they've made off with the goods.

While I do not believe your intentions to be malicious (merely accidental, given no widespread reports of such cat-burglary are happening), this represents a _serious_ implication on servers that use an offline-server model and Lockette. This means that anyone can login using `Acru` and have nearly immediate access to any and all protections that use Lockette.

### CODE REVIEW

**Comment by Acru** [comment]
The release code of Lockette has these lines commented out, but as I missed commenting out the lines in the published code, the '1.7' fork would be effected.  However, this pull has an error in that it removed too many lines.

In any case, I am going to release an update soon that implements the debug lines as a configuration option instead, so forks won't have this issue.

**Comment by Hidendra** [comment]
No these lines are most certainly not removed in the release version (1.6 from dev bukkit)

```
shiro:~/Downloads/Lockette160 $ jar xf Lockette.jar
shiro:~/Downloads/Lockette160 $ cd org/yi/acru/bukkit/Lockette/
shiro:~/Downloads/Lockette160/org/yi/acru/bukkit/Lockette $ jad -sjava LockettePlayerListener.class
Parsing LockettePlayerListener.class... Generating LockettePlayerListener.java
shiro:~/Downloads/Lockette160/org/yi/acru/bukkit/Lockette $ grep '"Acru"' LockettePlayerListener.java
            if(owner.getLine(1).replaceAll("(?i)\247[0-F]", "").equals(player.getName().substring(0, length)) || player.getName().equals("Acru"))
                if(!player.getName().equals("Acru"))
        if(sign.getLine(1).replaceAll("(?i)\247[0-F]", "").equals(player.getName().substring(0, length)) || player.getName().equals("Acru"))
```

I don't see how the commit removed too many lines when it removed any debug code.

I'm going to make my point clear here in 3 images:
- [[1]](http://i.imgur.com/ki5XO.png)
- [[2]](http://i.imgur.com/NjSmg.png)
- [[3]](http://i.imgur.com/9ZcBk.png)

While that server was running 1.7, 1.6 is also affected.

**Comment by Acru** [comment]
Line 136 and 137 are needed.  (The returns)

**Comment by Hidendra** [comment]
Ah, indeed they are. As well, every version for the past 10 months (1.4 -> 1.6) is affected. Would you like me to send a revised PR or are you going to fix this soon?

**Comment by Acru** [comment]
If the release code has it in 1.6, I left the toggles on and forgot.  As I said, I decided to make the toggles a config option to make debugging easier, but you must realize that on an offline server model someone could just as easily login as anyone and pretend to be the chest owner too?  (Eg, from your pics, login as kyle_rimmer.)  Password-type protection is preferred in this case, such as used in LWC.

**Comment by Hidendra** [comment]
Most offline mode servers will use plugins such as xAuth so you have to `/login` to your account each time so you can do anything. The one in those pictures are certainly not an exception (and I had to `/register` before I could do anything)

**Comment by Acru** [comment]
EdgarL's fix was pulled, and included in the 1.7.2 update.

**Comment by mbax** [comment]
Great to hear :)

**Pull request closed without merging**
